# Specifies base image and tag
FROM gcr.io/deeplearning-platform-release/tf2-gpu.2-2
WORKDIR /root

# Installs additional packages
RUN pip install seaborn

# Add /root to python path
ENV PYTHONPATH "${PYTHONPATH}:/root"

# Copy the code to the docker image.
COPY train_fast_rcnn.py /root/train_fast_rcnn.py

RUN mkdir -p /root/data
COPY data/__init__.py /root/data/__init__.py
COPY data/input_pipeline.py /root/data/input_pipeline.py
COPY data/kitti_classes.py /root/data/kitti_classes.py

COPY models /root/models
COPY utils /root/utils

# Sets up the entry point to invoke the trainer.
ENTRYPOINT ["python3", "train_fast_rcnn.py"]